name: ${project.name}
main: mc.adambor.ArenaPlunger.ArenaPlungerPlugin
version: ${project.version}
author: adambor
depend: [BattleArena]
description: ${project.description}
commands:
  ap:
    description: Arena Plunger
    aliases: [ap]
    usage: /ap <setPlunger, setMaterial, setEffect>
