name: ArenaPlunger
main: mc.adambor.ArenaPlunger.Main
version: 0.0.1
author: adambor
depend: [BattleArena]
description: Version 0 of ArenaPlunger
commands:
  ap:
    description: Arena Plunger
    aliases: [ap]
    usage: /ap <setPlunger, setMaterial, setEffect>
